name: Build and deploy Node.js app to Azure Web App - Webwizardz-Frontend

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Strip sourcemaps (kleinere zip)
        run: find dist -name "*.map" -type f -delete

      - name: Create release.zip
        run: |
          cd dist
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:      ${{ secrets.AZUREAPPSERVICE_CLIENTID_CFC43901334344C88848C741C7743132 }}
          tenant-id:      ${{ secrets.AZUREAPPSERVICE_TENANTID_C2B0ABEA92014C4DBC8FD7F48134F1EA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_930B37F0FD8B4C76A7862CF01A607428 }}

      - name: Stop Web App
        run: az webapp stop --name Webwizardz-Frontend --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: Deploy release.zip
        id: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: Webwizardz-Frontend
          slot-name: Production
          package: release.zip

      - name: Start Web App
        run: az webapp start --name Webwizardz-Frontend --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
